import React from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, Check, MapPin, Percent, ShieldCheck, Users } from "lucide-react";
import { PublicHeader, UnifiedFooter } from "./LandingHub";

const offers=[
 {t:"Tarifs négociés",s:"Des conditions obtenues collectivement sur des besoins récurrents.",items:["Assurance professionnelle","SaaS et outils métier","Banque / paiement","Coworking et services récurrents"],tag:"Permanent"},
 {t:"Business Travel",s:"Des offres ponctuelles pour travailler et bouger dans de bonnes conditions.",items:["Coworking à la journée","Hôtels business","Salles de réunion","Airport lounges"],tag:"Offres limitées"},
 {t:"Offres du moment",s:"Des avantages ponctuels sélectionnés parce qu'ils sont utiles à l'activité.",items:["Événements","Formations","Expériences","Bien-être professionnel"],tag:"Découverte"},
];
export default function Avantages(){return <div className="min-h-screen" style={{background:"#f6f3ee"}}><Helmet><title>Avantages Zayado | Tarifs négociés & Business Travel</title><meta name="description" content="Découvrez les avantages Zayado : tarifs négociés pour indépendants et petites structures, offres Business Travel et opportunités ponctuelles sélectionnées."/><link rel="canonical" href="https://zayado.net/avantages"/><meta name="robots" content="index,follow"/></Helmet><PublicHeader/><main><section className="text-white" style={{background:"linear-gradient(120deg,#102945,#1f3a5f)"}}><div className="max-w-6xl mx-auto px-4 md:px-6 py-16 md:py-24"><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/8 px-3 py-1.5 text-xs uppercase tracking-widest"><Users size={14}/> Avantages Zayado</div><h1 className="mt-5 text-4xl md:text-6xl max-w-4xl font-serif">Des avantages pensés pour la vraie vie d'un indépendant.</h1><p className="mt-5 max-w-2xl text-white/75 text-lg">La mutualisation reste la mécanique derrière les tarifs collectifs. Les offres ponctuelles et le Business Travel vivent à côté, clairement identifiés.</p></div></section><section className="max-w-6xl mx-auto px-4 md:px-6 py-14"><div className="grid lg:grid-cols-3 gap-5">{offers.map((o,i)=><article key={o.t} className="bg-white rounded-[26px] border border-[#e4dccd] p-7"><div className="flex justify-between items-start"><div className="w-12 h-12 rounded-2xl bg-[#f1e6d0] grid place-items-center" style={{color:"#a18145"}}>{i===0?<Percent size={22}/>:i===1?<MapPin size={22}/>:<ShieldCheck size={22}/>}</div><span className="text-[10px] uppercase tracking-widest rounded-full px-2.5 py-1 bg-[#f6f0e4] text-[#8e7041]">{o.tag}</span></div><h2 className="mt-5 text-2xl font-serif">{o.t}</h2><p className="mt-2 text-sm text-[#70675c]">{o.s}</p><div className="mt-5 space-y-2">{o.items.map(x=><div key={x} className="flex gap-2 text-sm"><Check size={15} className="mt-0.5" style={{color:"#a18145"}}/>{x}</div>)}</div></article>)}</div></section><section className="max-w-6xl mx-auto px-4 md:px-6 pb-16"><div className="rounded-[28px] bg-[#fbf8f1] border border-[#e5dccb] p-7 md:p-10"><div className="text-xs uppercase tracking-widest text-[#a18145]">Règle Zayado</div><h2 className="mt-2 text-3xl font-serif">Une offre n'est visible que lorsque sa valeur est vérifiable.</h2><p className="mt-4 max-w-3xl text-[#70675c]">Chaque offre doit indiquer si elle est permanente ou limitée dans le temps, et préciser ce que Zayado a réellement vérifié : prix, conditions, disponibilité ou partenaire.</p><Link to="/boutique" className="inline-flex mt-6 items-center gap-2 rounded-full bg-[#102945] text-white px-5 py-3 text-sm font-semibold">Voir la boutique <ArrowRight size={15}/></Link></div></section></main><UnifiedFooter/></div>}
