import React from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, ChevronDown, Sparkles } from "lucide-react";

const GOLD = "#E3C887";
const GOLD_DARK = "#B8873C";
const NAVY = "#071B3A";
const NAVY_2 = "#163B63";
const PANEL = "#102A4A";
const PANEL_2 = "#17385D";
const TEXT = "#F7F4EC";
const MUTED = "#BFCBDA";

const modules = [
  ["Vision Board", "Transformez votre ambition en trajectoire claire.", "Vision"],
  ["DAF IA", "Lisez vos chiffres et préparez vos décisions financières.", "Finance"],
  ["Espace de travail", "Missions, documents et priorités au même endroit.", "Work"],
  ["Growth Agent", "Structurez vos actions d'acquisition et de croissance.", "Growth"],
  ["CRM", "Conservez le contexte de vos relations et opportunités.", "CRM"],
  ["Énergie", "Reliez votre organisation à votre rythme réel.", "Energy"],
];

function Brand(){return <Link to="/myextension-ai" className="flex items-center gap-2"><span className="w-7 h-7 rounded-md grid place-items-center bg-[#173B62] border border-white/10 text-[#E3C887] font-black">Z</span><span className="font-semibold tracking-wide text-white">MYEXTENSION AI</span></Link>}
function MiniNav(){return <div className="flex items-center gap-6 text-xs text-white/70"><Link to="/myextension-ai">Accueil</Link><Link to="/boutique">Zayado</Link><Link to="/tarifs">Tarifs</Link><Link to="/faq">FAQ</Link></div>}

function DashboardMock(){return <div className="rounded-2xl border border-white/10 bg-[#0F2744] shadow-2xl overflow-hidden"><div className="px-4 py-3 border-b border-white/10 flex items-center justify-between"><div className="text-xs text-white/60">MyExtension AI · Cockpit</div><div className="w-2 h-2 rounded-full" style={{background:"linear-gradient(135deg,#f4e6c5,#c89b52)"}}/></div><div className="grid grid-cols-12 gap-3 p-4"><div className="col-span-4 space-y-3"><div className="rounded-xl bg-[#17385D] p-4"><div className="text-[10px] text-white/40">SCORE BUSINESS</div><div className="text-3xl font-semibold mt-1">78<span className="text-sm text-white/35">/100</span></div><div className="mt-3 h-1.5 rounded-full bg-white/5"><div className="h-full w-[78%] rounded-full" style={{background:"linear-gradient(135deg,#f4e6c5,#c89b52)"}}/></div></div><div className="rounded-xl bg-[#17385D] p-4"><div className="text-[10px] text-white/40">TRÉSORERIE</div><div className="text-xl font-semibold mt-1">12 480 €</div><div className="text-xs mt-2" style={{color:GOLD}}>+8,4 %</div></div></div><div className="col-span-8 space-y-3"><div className="rounded-xl bg-[#17385D] p-4 h-40"><div className="flex justify-between text-[10px] text-white/40"><span>ACTIVITÉ</span><span>30 jours</span></div><div className="h-[110px] mt-2 relative"><svg viewBox="0 0 600 160" className="w-full h-full"><polyline fill="none" stroke={GOLD} strokeWidth="4" points="0,120 70,100 120,110 180,78 220,84 280,50 340,70 400,35 460,50 520,25 600,40"/></svg></div></div><div className="grid grid-cols-3 gap-3">{[["Priorités","4"],["Missions","12"],["Décisions","3"]].map(([a,b])=><div key={a} className="rounded-xl bg-[#17385D] p-3"><div className="text-[10px] text-white/40">{a}</div><div className="text-lg font-semibold mt-1">{b}</div></div>)}</div></div></div></div>}

export default function MyExtensionAI(){
  return <div className="min-h-screen" style={{background:NAVY,color:TEXT}}>
    <Helmet><title>MyExtension AI | Le cockpit business de Zayado</title><meta name="description" content="MyExtension AI relie vision, pilotage financier, travail, CRM, croissance et énergie dans un cockpit business unique."/><link rel="canonical" href="https://zayado.net/myextension-ai"/><meta name="robots" content="index,follow"/></Helmet>

    <header className="sticky top-0 z-40 bg-[#071B3A]/92 backdrop-blur border-b border-white/10"><div className="max-w-7xl mx-auto px-5 md:px-8 h-16 flex items-center justify-between"><Brand/><div className="hidden md:block"><MiniNav/></div><Link to="/tarifs" className="rounded-full px-4 py-2 text-xs font-semibold text-[#102945]" style={{background:"linear-gradient(135deg,#f4e6c5,#c89b52)"}}>Voir les tarifs</Link></div></header>

    <main>
      <section className="relative overflow-hidden"><div className="absolute inset-0 opacity-25" style={{backgroundImage:"radial-gradient(circle at 30% 15%, rgba(227,200,135,.7) 0 2px, transparent 2px), radial-gradient(circle at 70% 30%, rgba(227,200,135,.7) 0 2px, transparent 2px)",backgroundSize:"160px 160px"}}/><div className="relative max-w-6xl mx-auto px-5 md:px-8 pt-20 md:pt-28 text-center"><div className="text-[10px] tracking-[.28em] uppercase font-semibold" style={{color:GOLD}}>Préparez moins. Décidez mieux.</div><h1 className="mt-5 text-5xl md:text-7xl font-semibold leading-[.95] tracking-tight">Votre cockpit business<br/><span style={{color:GOLD}}>augmenté par l'IA.</span></h1><p className="mt-6 max-w-2xl mx-auto text-base md:text-lg text-white/60">Vision, finance, travail, CRM, croissance et énergie réunis autour de votre contexte réel.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="https://app.zayado.net/login" className="rounded-full px-5 py-3 text-sm font-semibold text-[#102945]" style={{background:"linear-gradient(135deg,#f4e6c5,#c89b52)"}}>Ouvrir MyExtension AI <ArrowRight size={15} className="inline ml-2"/></a><Link to="/tarifs" className="rounded-full border border-white/15 px-5 py-3 text-sm font-semibold text-white/85">Comparer les offres</Link></div></div><div className="max-w-5xl mx-auto px-5 md:px-8 mt-14"><DashboardMock/></div></section>

      <section className="max-w-6xl mx-auto px-5 md:px-8 pt-24 pb-8 text-center"><div className="text-[10px] uppercase tracking-[.28em] font-semibold" style={{color:GOLD}}>Le pouvoir derrière le cockpit</div><h2 className="mt-3 text-4xl md:text-5xl font-semibold">Tout votre business au même endroit</h2><p className="mt-4 max-w-2xl mx-auto text-white/65">Une extension conçue pour réduire la dispersion entre vos outils et vos décisions.</p></section>
      <section className="max-w-6xl mx-auto px-5 md:px-8 pb-20 grid md:grid-cols-2 lg:grid-cols-3 gap-4">{modules.map(([title,desc,tag])=><article key={title} className="rounded-2xl border border-white/10 bg-[#102A4A] p-6"><div className="text-[10px] uppercase tracking-widest" style={{color:GOLD}}>{tag}</div><h3 className="mt-4 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{desc}</p><div className="mt-6 flex items-center gap-2 text-xs text-white/60"><CheckCircle2 size={15} style={{color:GOLD}}/> Conçu pour votre contexte réel</div></article>)}</section>

      <section className="border-y border-white/10 bg-[#0C2440]"><div className="max-w-6xl mx-auto px-5 md:px-8 py-20 grid lg:grid-cols-2 gap-12 items-center"><div><div className="text-[10px] uppercase tracking-[.28em] font-semibold" style={{color:GOLD}}>Copilote</div><h2 className="mt-3 text-4xl font-semibold">Une IA qui montre ce qu'elle prend en compte.</h2><p className="mt-5 text-white/65">Le Copilote s'appuie sur les données réellement disponibles dans votre espace : tâches, objectif, missions et décisions en attente.</p><div className="mt-6 grid grid-cols-2 gap-3">{['Vos 3 dernières tâches','Votre objectif','1 décision en attente','Votre contexte projet'].map(x=><div key={x} className="rounded-xl bg-[#183A5F] border border-white/10 p-3 text-xs text-white/70">✓ {x}</div>)}</div></div><div className="rounded-3xl border border-white/10 bg-[#143456] p-6"><div className="text-xs text-white/60">COPILOTE · APERÇU</div><div className="mt-5 text-sm text-white/80">“Vous avez avancé sur votre mission principale, mais la décision commerciale est encore bloquée. Voici les 2 actions prioritaires.”</div><div className="mt-5 grid gap-2"><div className="rounded-xl bg-[#17385D] p-3 text-xs">01 · Préparer la relance de l'opportunité</div><div className="rounded-xl bg-[#17385D] p-3 text-xs">02 · Valider le budget de la semaine</div></div></div></div></section>

      <section className="max-w-6xl mx-auto px-5 md:px-8 py-20"><div className="text-[10px] uppercase tracking-[.28em] font-semibold text-center" style={{color:GOLD}}>Votre parcours</div><h2 className="mt-3 text-4xl md:text-5xl font-semibold text-center">Comment commencer</h2><div className="grid md:grid-cols-3 gap-4 mt-10">{[['01','Branchez votre activité','Créez votre espace et définissez votre objectif.'],['02','Travaillez dans le cockpit','Missions, documents, CRM et pilotage au même endroit.'],['03','Laissez l’IA préparer','Recevez des recommandations contextualisées et gardez la décision.']].map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/10 bg-[#102A4A] p-6"><div className="text-sm" style={{color:GOLD}}>{n}</div><h3 className="mt-5 text-2xl font-semibold">{t}</h3><p className="mt-3 text-sm text-white/65 leading-relaxed">{d}</p></div>)}</div></section>

      <section className="max-w-6xl mx-auto px-5 md:px-8 pb-20"><div className="rounded-3xl border border-white/10 bg-[#102A4A] p-8 md:p-12"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.28em] font-semibold" style={{color:GOLD}}><Sparkles size={13}/> Témoignage</div><blockquote className="mt-5 max-w-4xl text-2xl md:text-3xl leading-snug text-white/90">“Enfin un cockpit où je retrouve ce dont j'ai besoin sans ouvrir cinq outils différents.”</blockquote><div className="mt-6 text-xs text-white/60">Exemple de mise en situation · indépendant</div></div></section>

      <section className="border-y border-white/10 bg-gradient-to-b from-[#102A4A] to-[#0B2440]"><div className="max-w-6xl mx-auto px-5 md:px-8 py-20 text-center"><div className="text-[10px] uppercase tracking-[.28em] font-semibold" style={{color:GOLD}}>Des offres séparées</div><h2 className="mt-3 text-4xl md:text-5xl font-semibold">Choisissez votre niveau d'accompagnement</h2><p className="mt-4 max-w-2xl mx-auto text-white/65">La tarification complète est présentée sur une page dédiée pour garder cette page centrée sur la valeur du produit.</p><Link to="/tarifs" className="mt-8 inline-flex rounded-full px-6 py-3 text-sm font-semibold text-[#102945]" style={{background:"linear-gradient(135deg,#f4e6c5,#c89b52)"}}>Voir la page Tarifs <ArrowRight size={15} className="inline ml-2"/></Link></div></section>

      <section className="max-w-6xl mx-auto px-5 md:px-8 py-20"><div className="text-center"><div className="text-[10px] uppercase tracking-[.28em] font-semibold" style={{color:GOLD}}>FAQ</div><h2 className="mt-3 text-4xl font-semibold">Questions fréquentes</h2></div><div className="mt-10 max-w-4xl mx-auto divide-y divide-white/7 border-y border-white/10">{[['MyExtension AI remplace-t-il mes autres outils ?','Il cherche d’abord à relier votre contexte et vos décisions ; les outils externes peuvent rester connectés.'],['L’IA prend-elle les décisions à ma place ?','Non. MyExtension AI prépare, structure et recommande ; vous gardez la décision.'],['Mes données sont-elles inventées ?','Le principe produit est de ne pas afficher une information comme réelle lorsqu’elle ne l’est pas.']].map(([q,a])=><details key={q} className="py-5 group"><summary className="list-none cursor-pointer flex items-center justify-between gap-4 text-sm font-medium"><span>{q}</span><ChevronDown size={17} className="transition group-open:rotate-180"/></summary><p className="mt-3 pr-8 text-sm text-white/65 leading-relaxed">{a}</p></details>)}</div></section>

      <section className="border-t border-white/10"><div className="max-w-6xl mx-auto px-5 md:px-8 py-12 flex flex-col md:flex-row items-center justify-between gap-6"><div><div className="text-2xl md:text-3xl font-semibold">L'IA prépare. <span style={{color:GOLD}}>Vous décidez.</span></div><p className="mt-2 text-sm text-white/65">Découvrez le cockpit business de Zayado.</p></div><div className="flex gap-3"><a href="https://app.zayado.net/login" className="rounded-full px-5 py-3 text-sm font-semibold text-[#102945]" style={{background:"linear-gradient(135deg,#f4e6c5,#c89b52)"}}>Ouvrir l'app</a><Link to="/contact" className="rounded-full border border-white/15 px-5 py-3 text-sm font-semibold">Nous contacter</Link></div></div></section>
    </main>
    <footer className="border-t border-white/10"><div className="max-w-6xl mx-auto px-5 md:px-8 py-10 grid md:grid-cols-4 gap-8 text-sm"><div><Brand/></div><div><div className="text-white/40 uppercase text-[10px] tracking-widest">Produit</div><Link to="/myextension-ai" className="block mt-3 text-white/65">Fonctionnalités</Link><Link to="/tarifs" className="block mt-2 text-white/65">Tarifs</Link></div><div><div className="text-white/40 uppercase text-[10px] tracking-widest">Zayado</div><Link to="/boutique" className="block mt-3 text-white/65">Marketplace</Link><Link to="/nos-services" className="block mt-2 text-white/65">Services</Link></div><div><div className="text-white/40 uppercase text-[10px] tracking-widest">Support</div><Link to="/faq" className="block mt-3 text-white/65">FAQ</Link><Link to="/contact" className="block mt-2 text-white/65">Contact</Link></div></div><div className="border-t border-white/10 max-w-6xl mx-auto px-5 md:px-8 py-4 text-xs text-white/35">© 2026 Zayado · MyExtension AI</div></footer>
  </div>
}
