import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Briefcase, CalendarDays, Check, CheckCircle2, Circle, Clock3, FileText, FolderKanban, ListChecks, Loader2, Pencil, Play, Plus, RotateCcw, Square, Target, Trash2, TrendingUp, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { createDocumentTravail, createProjet, createTache, deleteDocumentTravail, deleteProjet, deleteTache, getDocumentsTravail, getHumeur, getProjets, getTaches, startProjectTimer, stopProjectTimer, updateTache, updateTacheStatut } from "../lib/api";

const VIEWS = [["maintenant", "Maintenant", Zap], ["engagements", "Engagements", ListChecks], ["projets", "Projets", FolderKanban], ["semaine", "Semaine", CalendarDays], ["resultats", "Résultats", TrendingUp], ["ressources", "Ressources", FileText]];
const STATUS = ["A faire", "En cours", "Terminé"];
const today = () => new Date().toISOString().slice(0, 10);
const done = (task) => task.statut === "Terminé";
const rank = (task) => ({ Haute: 0, Moyenne: 1, Normale: 2, Basse: 3 })[task.priorite] ?? 2;
const priorityCode = (priority) => ({ Haute: "high", Moyenne: "medium", Normale: "normal", Basse: "low", high: "high", medium: "medium", normal: "normal", low: "low" })[priority] || "normal";
const tone = (energy) => energy == null ? ["À renseigner", "#93c5fd", "Ajoutez un check-in pour ajuster la journée."] : energy < 45 ? ["À protéger", "#fb7185", "Réduisez la charge non essentielle."] : energy < 65 ? ["Mesurée", "#fcd34d", "Une priorité principale suffit aujourd’hui."] : ["Disponible", "#34d399", "Gardez une marge avant d’ajouter une mission."];

function Empty({ icon: Icon, title, text }) {
  return <div className="flex min-h-[150px] flex-col items-center justify-center rounded-xl border border-dashed border-white/15 bg-white/[0.025] px-5 text-center"><Icon size={18} className="mb-3 text-[#F1E2CC]" /><p className="font-head text-sm font-semibold text-white">{title}</p><p className="mt-1 max-w-sm text-xs leading-5 text-white/45">{text}</p></div>;
}

function TaskLine({ task, project, projects = [], onCycle, onDelete, onToday, onUpdated }) {
  const [editing, setEditing] = useState(false);
  const [label, setLabel] = useState(task.titre);
  const [priority, setPriority] = useState(task.priorite || "Normale");
  const [projectId, setProjectId] = useState(task.project_id || "");
  const [plannedFor, setPlannedFor] = useState(task.planned_for || "");
  const icon = task.statut === "Terminé" ? <CheckCircle2 size={17} /> : task.statut === "En cours" ? <Clock3 size={17} /> : <Circle size={17} />;
  const color = task.statut === "Terminé" ? "#34d399" : task.statut === "En cours" ? "#fcd34d" : "#93c5fd";
  const overdue = task.planned_for && task.planned_for < today() && !done(task);
  const strategicSource = task.strategic_milestone_id ? "Jalon stratégique" : task.decision_id ? "Décision validée" : task.vision_pillar_id ? `Pilier · ${task.vision_pillar_id}` : "";
  const startEdit = () => { setLabel(task.titre); setPriority(task.priorite || "Normale"); setProjectId(task.project_id || ""); setPlannedFor(task.planned_for || ""); setEditing(true); };
  const save = async () => {
    if (!label.trim()) return toast.error("Le titre est requis.");
    try {
      await updateTache(task.id, {
        label: label.trim(),
        priority: priorityCode(priority),
        project_id: projectId || null,
        planned_for: plannedFor || null,
      });
      setEditing(false); onUpdated(); toast.success("Engagement modifié.");
    } catch { toast.error("Modification impossible."); }
  };
  return <div className={`flex items-start gap-3 rounded-xl border bg-white/[0.035] px-3.5 py-3 ${overdue ? "border-rose-300/35" : "border-white/10"}`}><button onClick={() => onCycle(task)} style={{ color }} title="Changer le statut" className="mt-0.5 shrink-0">{icon}</button><div className="min-w-0 flex-1">{editing ? <div className="flex flex-col gap-2">
      <input value={label} onChange={(e) => setLabel(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-white/15 bg-white/5 px-2 py-1 text-sm text-white" autoFocus />
      <div className="flex flex-wrap gap-2">
        <select value={priority} onChange={(e) => setPriority(e.target.value)} className="rounded-lg border border-white/15 bg-white/5 px-2 py-1 text-xs text-white"><option>Haute</option><option>Moyenne</option><option>Normale</option><option>Basse</option></select>
        <select value={projectId} onChange={(e) => setProjectId(e.target.value)} className="rounded-lg border border-white/15 bg-white/5 px-2 py-1 text-xs text-white"><option value="">Sans projet</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select>
        <input type="date" value={plannedFor} onChange={(e) => setPlannedFor(e.target.value)} className="rounded-lg border border-white/15 bg-white/5 px-2 py-1 text-xs text-white" />
        {plannedFor && <button type="button" onClick={() => setPlannedFor("")} className="rounded-lg border border-white/15 px-2 py-1 text-[10px] text-white/55 hover:text-white">Retirer la date</button>}
      </div>
    </div> : <p className={`break-words text-sm ${done(task) ? "text-white/40 line-through" : "text-white/88"}`}>{task.titre}</p>}<p className="mt-1 text-[11px] text-white/42">{project?.name || "Sans projet"}{task.estimated_minutes ? ` · ${task.estimated_minutes} min` : ""}{task.planned_for ? ` · ${task.planned_for === today() ? "Aujourd’hui" : task.planned_for}` : ""}</p><div className="mt-1 flex flex-wrap items-center gap-2"><span className="text-[10px] font-semibold text-[#DEC2A3]">Priorité {task.priorite || "Normale"}</span>{overdue && <span className="text-[10px] font-semibold text-rose-300">En retard</span>}{strategicSource && <span className="text-[10px] font-semibold text-[#DEC2A3]">{strategicSource}</span>}</div></div>{!editing && !task.planned_for && !done(task) && <button onClick={() => onToday(task)} title="Planifier cette tâche pour aujourd'hui" className="inline-flex items-center gap-1 rounded-lg border border-dashed border-white/20 px-2 py-1 text-[10px] font-medium text-white/50 hover:border-[#DEC2A3]/60 hover:text-[#DEC2A3]">+ Planifier aujourd’hui</button>}{editing ? <><button onClick={save} title="Enregistrer" className="text-emerald-300"><Check size={15} /></button><button onClick={() => setEditing(false)} title="Annuler" className="text-white/40"><X size={15} /></button></> : <button onClick={startEdit} title="Modifier" className="text-white/40 hover:text-[#DEC2A3]"><Pencil size={14} /></button>}<button onClick={() => window.confirm("Supprimer cet engagement ?") && onDelete(task.id)} title="Supprimer" className="text-white/30 hover:text-rose-300"><Trash2 size={14} /></button></div>;
}

function Composer({ projects, onCreated }) {
  const [label, setLabel] = useState(""); const [projectId, setProjectId] = useState(""); const [minutes, setMinutes] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { if (!label.trim()) return; setSaving(true); try { await createTache({ titre: label.trim(), project_id: projectId || null, planned_for: today(), estimated_minutes: minutes || null }); setLabel(""); setMinutes(""); setProjectId(""); toast.success("Engagement ajouté."); onCreated(); } catch { toast.error("Impossible d’ajouter cet engagement."); } finally { setSaving(false); } };
  return <div className="grid gap-2 md:grid-cols-[1.3fr_.75fr_.4fr_auto]"><input value={label} onChange={(e) => setLabel(e.target.value)} onKeyDown={(e) => e.key === "Enter" && submit()} placeholder="Nouvel engagement concret…" className="min-w-0 rounded-xl border border-white/15 bg-white/5 px-3.5 py-2.5 text-sm text-white placeholder:text-white/35 focus:outline-none" /><select value={projectId} onChange={(e) => setProjectId(e.target.value)} className="rounded-xl border border-white/15 bg-white/5 px-3 py-2.5 text-sm text-white/80"><option value="">Sans projet</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input value={minutes} onChange={(e) => setMinutes(e.target.value.replace(/\D/g, ""))} inputMode="numeric" placeholder="min." className="rounded-xl border border-white/15 bg-white/5 px-3 py-2.5 text-sm text-white placeholder:text-white/35 focus:outline-none" /><button onClick={submit} disabled={saving} className="inline-flex items-center justify-center gap-1.5 rounded-xl bg-[#DEC2A3] px-4 py-2.5 text-sm font-bold text-[#0A1128] disabled:opacity-60">{saving ? <Loader2 size={14} className="animate-spin" /> : <Plus size={15} />}Ajouter</button></div>;
}

export default function Travail({ initialView = "maintenant" }) {
  const [view, setView] = useState(initialView); const [tasks, setTasks] = useState([]); const [projects, setProjects] = useState([]); const [documents, setDocuments] = useState([]); const [moods, setMoods] = useState([]); const [loading, setLoading] = useState(true); const [projectName, setProjectName] = useState(""); const [docName, setDocName] = useState(""); const [docUrl, setDocUrl] = useState(""); const [taskFilter, setTaskFilter] = useState("all");
  const load = async () => { setLoading(true); const r = await Promise.allSettled([getTaches(), getProjets(), getDocumentsTravail(), getHumeur()]); if (r[0].status === "fulfilled") setTasks(r[0].value || []); else if (r[0].reason?.response?.status !== 401 && r[0].reason?.response?.status !== 403) toast.error("Impossible de charger les engagements."); if (r[1].status === "fulfilled") setProjects(r[1].value || []); if (r[2].status === "fulfilled") setDocuments(r[2].value || []); if (r[3].status === "fulfilled") setMoods(r[3].value || []); setLoading(false); };
  useEffect(() => { load(); }, []);
  const byProject = useMemo(() => Object.fromEntries(projects.map((p) => [p.id, p])), [projects]); const open = useMemo(() => tasks.filter((t) => !done(t)).sort((a, b) => rank(a) - rank(b)), [tasks]); const filteredOpen = useMemo(() => open.filter((t) => taskFilter === "all" || (taskFilter === "today" && t.planned_for === today()) || (taskFilter === "overdue" && t.planned_for && t.planned_for < today()) || (taskFilter === "high" && t.priorite === "Haute")), [open, taskFilter]); const planned = filteredOpen.filter((t) => t.planned_for === today()); const primary = planned[0] || filteredOpen[0] || null; const toArbitrate = useMemo(() => filteredOpen.filter((t) => t.planned_for !== today()), [filteredOpen]); const energy = moods[0]?.energie ?? null; const [capacityLabel, capacityColor, capacityText] = tone(energy); const plannedMinutes = planned.reduce((s, t) => s + Number(t.estimated_minutes || 0), 0);
  const cycle = async (task) => { const next = STATUS[(Math.max(0, STATUS.indexOf(task.statut)) + 1) % STATUS.length]; setTasks((all) => all.map((t) => t.id === task.id ? { ...t, statut: next } : t)); try { await updateTacheStatut(task.id, next); } catch { toast.error("Mise à jour impossible."); load(); } };
  const planToday = async (task) => { try { await updateTache(task.id, { planned_for: today() }); await load(); toast.success("Planifié pour aujourd’hui."); } catch { toast.error("Planification impossible."); } };
  const removeTask = async (id) => { try { await deleteTache(id); await load(); } catch { toast.error("Suppression impossible."); } };
  const addProject = async () => { if (!projectName.trim()) return; try { await createProjet({ name: projectName.trim() }); setProjectName(""); await load(); } catch { toast.error("Création du projet impossible."); } };
  const removeProject = async (id) => { try { await deleteProjet(id); await load(); } catch { toast.error("Suppression impossible."); } };
  const timer = async (p) => { try { p.is_running ? await stopProjectTimer(p.id) : await startProjectTimer(p.id); await load(); } catch { toast.error("Minuteur indisponible."); } };
  const addDocument = async () => { if (!docName.trim()) return; try { await createDocumentTravail({ nom: docName.trim(), url: docUrl.trim() }); setDocName(""); setDocUrl(""); await load(); } catch { toast.error("Ajout de la ressource impossible."); } };
  const removeDocument = async (id) => { try { await deleteDocumentTravail(id); await load(); } catch { toast.error("Suppression impossible."); } };
  if (loading) return <div className="flex justify-center py-24"><Loader2 size={24} className="animate-spin text-white/45" /></div>;
  const totalTime = projects.reduce((s, p) => s + Number(p.total_time_seconds || 0), 0); const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() + i); return d; });
  return <div className="space-y-6" data-testid="page-travail"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#DEC2A3]">Exécution consciente</p><h1 className="mt-1 font-head text-2xl font-semibold text-white">Mon Mouvement</h1><p className="mt-1 text-sm text-white/55">Du Cap à une action soutenable, puis à une preuve réelle.</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.055] px-4 py-3 sm:w-[270px]"><div className="flex justify-between text-xs font-semibold text-white/72"><span>Capacité du jour</span><span style={{ color: capacityColor }}>{energy == null ? "—" : `${energy}/100`}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full" style={{ width: `${energy || 0}%`, background: capacityColor }} /></div><p className="mt-2 text-[11px] text-white/45">{capacityText}</p></div></header>
    <nav className="overflow-x-auto pb-1"><div className="flex min-w-max gap-2">{VIEWS.map(([id, label, Icon]) => <button key={id} onClick={() => setView(id)} className={`inline-flex items-center gap-2 rounded-full border px-3.5 py-2 text-sm font-semibold transition ${view === id ? "border-[#DEC2A3]/40 bg-[#DEC2A3] text-[#0A1128]" : "border-white/15 bg-white/[0.04] text-white/65 hover:text-white"}`}><Icon size={14} />{label}</button>)}</div></nav>
    {view === "maintenant" && <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><section className="glass p-5"><p className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.15em] text-[#F1E2CC]"><Zap size={15} />Mission principale</p>{primary ? <><div className="mt-5 flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-[#DEC2A3]/30 bg-[#DEC2A3]/10 text-[#F1E2CC]"><Target size={19} /></span><div><h2 className="font-head text-xl font-semibold text-white">{primary.titre}</h2><p className="mt-2 text-sm leading-6 text-white/55">{byProject[primary.project_id]?.name ? `Ce mouvement sert le projet « ${byProject[primary.project_id].name} ». ` : "Reliez cette action à un projet lorsque le résultat le mérite. "}{primary.estimated_minutes ? `${primary.estimated_minutes} min estimées.` : "Gardez l’action courte et concrète."}</p></div></div><div className="mt-5 flex gap-2"><button onClick={() => cycle({ ...primary, statut: "A faire" })} className="inline-flex items-center gap-2 rounded-xl bg-[#DEC2A3] px-4 py-2.5 text-sm font-bold text-[#0A1128]"><Play size={14} />Commencer</button><button onClick={() => setView("engagements")} className="rounded-xl border border-white/15 px-4 py-2.5 text-sm font-semibold text-white/72">Voir les engagements <ArrowRight size={14} className="inline" /></button></div></> : <Empty icon={Target} title="Aucune mission à exécuter." text="Ajoutez un engagement ou validez une décision dans le Copilote." />}</section><aside className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><section className="glass p-5"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-white/48">Charge planifiée</p><p className="mt-3 font-head text-2xl font-semibold text-white">{plannedMinutes ? `${plannedMinutes} min` : "—"}</p><p className="mt-1 text-xs text-white/45">{planned.length ? `${planned.length} engagement(s) aujourd’hui.` : "Aucun engagement daté aujourd’hui."}</p></section><section className="glass p-5"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-white/48">Ensuite</p>{open.filter((t) => t.id !== primary?.id).slice(0, 2).map((t) => <p key={t.id} className="mt-3 truncate text-sm text-white/72">{t.titre}</p>) || <p className="mt-3 text-xs text-white/45">Préservez votre marge.</p>}</section></aside></div>}
    {view === "engagements" && <section className="glass p-5"><div className="mb-5 flex justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#F1E2CC]">Liste courte et actionnable</p><h2 className="mt-1 font-head text-lg font-semibold text-white">Engagements</h2></div><span className="text-xs text-white/45">{open.length} ouvert(s)</span></div><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><label className="text-xs text-white/55" htmlFor="task-filter">Afficher</label><select id="task-filter" value={taskFilter} onChange={(e) => setTaskFilter(e.target.value)} className="rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-xs text-white"><option value="all">Toutes les tâches</option><option value="today">Aujourd’hui</option><option value="overdue">En retard</option><option value="high">Priorité haute</option></select></div><Composer projects={projects} onCreated={load} /><div className="mt-5 grid gap-5 xl:grid-cols-2"><div><p className="mb-2 text-xs font-semibold text-white/58">Aujourd’hui</p><div className="space-y-2">{planned.length ? planned.map((t) => <TaskLine key={t.id} task={t} project={byProject[t.project_id]} projects={projects} onCycle={cycle} onDelete={removeTask} onToday={planToday} onUpdated={load} />) : <Empty icon={CalendarDays} title="Rien n’est daté aujourd’hui." text="Planifiez une action existante lorsque vous êtes prêt, ou ajustez le filtre « Afficher »." />}</div></div><div><p className="mb-2 text-xs font-semibold text-white/58">À arbitrer</p><div className="space-y-2">{toArbitrate.length ? toArbitrate.map((t) => <TaskLine key={t.id} task={t} project={byProject[t.project_id]} projects={projects} onCycle={cycle} onDelete={removeTask} onToday={planToday} onUpdated={load} />) : <Empty icon={ListChecks} title="Aucun engagement en attente." text="Les prochaines actions validées apparaîtront ici, ou aucune ne correspond au filtre actuel." />}</div></div></div></section>}
    {view === "projets" && <section className="space-y-4"><div className="glass flex gap-2 p-5"><input value={projectName} onChange={(e) => setProjectName(e.target.value)} onKeyDown={(e) => e.key === "Enter" && addProject()} placeholder="Nouveau projet orienté résultat…" className="min-w-0 flex-1 rounded-xl border border-white/15 bg-white/5 px-3.5 py-2.5 text-sm text-white placeholder:text-white/35" /><button onClick={addProject} className="rounded-xl bg-[#DEC2A3] px-4 py-2.5 text-sm font-bold text-[#0A1128]"><Plus size={14} className="inline" /> Créer</button></div>{projects.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((p) => { const list = tasks.filter((t) => t.project_id === p.id); const pct = list.length ? Math.round(list.filter(done).length / list.length * 100) : 0; return <article key={p.id} className="glass p-5"><div className="flex justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#DEC2A3]/25 bg-[#DEC2A3]/10 text-[#F1E2CC]"><Briefcase size={18} /></span><div className="flex gap-1"><button onClick={() => timer(p)} className="rounded-full bg-white/8 p-2 text-[#F1E2CC]">{p.is_running ? <Square size={13} /> : <Play size={13} />}</button><button onClick={() => removeProject(p.id)} className="p-2 text-white/35 hover:text-rose-300"><Trash2 size={14} /></button></div></div><h2 className="mt-4 font-head text-base font-semibold text-white">{p.name}</h2><p className="mt-1 text-xs text-white/45">{list.length ? `${list.filter(done).length}/${list.length} tâches terminées` : "Aucune tâche liée — le temps ci-dessous vient du minuteur du projet."}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#DEC2A3]" style={{ width: `${pct}%` }} /></div><p className="mt-3 text-[11px] text-white/42">{Math.floor(Number(p.total_time_seconds || 0) / 60)} min mesurées{p.is_running ? " · en cours" : ""}</p></article>; })}</div> : <div className="max-w-2xl"><Empty icon={FolderKanban} title="Aucun projet pour l’instant." text="Créez un projet seulement lorsqu’un résultat mérite plusieurs engagements." /></div>}</section>}
    {view === "semaine" && <section className="glass p-5"><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#F1E2CC]">Capacité avant ambition</p><h2 className="mt-1 font-head text-lg font-semibold text-white">Plan de semaine</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-7">{days.map((d) => { const day = d.toISOString().slice(0, 10); const list = open.filter((t) => t.planned_for === day); const active = day === today(); return <article key={day} className={`rounded-2xl border p-4 ${active ? "border-[#DEC2A3]/45 bg-[#DEC2A3]/[0.08]" : "border-white/12 bg-white/[0.03]"}`}><p className="text-xs font-semibold capitalize text-white">{new Intl.DateTimeFormat("fr-FR", { weekday: "short", day: "numeric" }).format(d)}</p><p className="mt-1 text-[11px]" style={{ color: active ? capacityColor : "rgba(255,255,255,.4)" }}>{active ? capacityLabel : "Capacité à renseigner"}</p><div className="mt-4 space-y-2">{list.length ? list.map((t) => <p key={t.id} className="rounded-lg bg-white/[0.06] px-2 py-2 text-xs text-white/72">{t.titre}</p>) : <p className="text-xs text-white/38">Aucun engagement planifié.</p>}</div></article>; })}</div></section>}
    {view === "resultats" && <section className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><div className="glass p-5"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-white/48">Tâches terminées</p><p className="mt-3 font-head text-3xl font-semibold text-white">{tasks.filter(done).length}</p><p className="mt-1 text-xs text-white/45">Tâches réellement présentes.</p></div><div className="glass p-5"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-white/48">Temps projet cumulé</p><p className="mt-3 font-head text-3xl font-semibold text-white">{totalTime ? `${Math.floor(totalTime / 3600)} h` : "—"}</p><p className="mt-1 text-xs text-white/45">Uniquement les minuteurs réels.</p></div><div className="glass p-5"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-white/48">Capacité renseignée</p><p className="mt-3 font-head text-3xl font-semibold text-white">{energy == null ? "—" : `${energy}/100`}</p><p className="mt-1 text-xs text-white/45">Issue du dernier check-in.</p></div></div><div className="glass flex gap-3 p-5"><RotateCcw size={17} className="mt-0.5 shrink-0 text-[#F1E2CC]" /><p className="text-sm leading-6 text-white/55">Ces indicateurs ne calculent ni une note de performance ni un diagnostic. Ils réunissent seulement les tâches terminées, le temps mesuré et la capacité renseignée pour aider à ajuster la semaine suivante.</p></div></section>}
    {view === "ressources" && <section className="glass p-5"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#F1E2CC]">Documents et preuves utiles</p><h2 className="mt-1 font-head text-lg font-semibold text-white">Ressources</h2></div><p className="max-w-sm text-xs text-white/45">Ajoutez une référence réelle. Aucun fichier de démonstration n’est créé.</p></div><div className="mt-5 grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input value={docName} onChange={(e) => setDocName(e.target.value)} placeholder="Nom de la ressource…" className="rounded-xl border border-white/15 bg-white/5 px-3.5 py-2.5 text-sm text-white placeholder:text-white/35" /><input value={docUrl} onChange={(e) => setDocUrl(e.target.value)} placeholder="Lien facultatif (https://…)" className="rounded-xl border border-white/15 bg-white/5 px-3.5 py-2.5 text-sm text-white placeholder:text-white/35" /><button onClick={addDocument} className="rounded-xl bg-[#DEC2A3] px-4 py-2.5 text-sm font-bold text-[#0A1128]"><Plus size={14} className="inline" /> Ajouter</button></div><div className="mt-5 grid gap-2 md:grid-cols-2">{documents.length ? documents.map((d) => <div key={d.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.035] px-3.5 py-3"><div className="flex min-w-0 items-center gap-2"><FileText size={16} className="shrink-0 text-[#F1E2CC]" />{d.url ? <a href={d.url} target="_blank" rel="noopener noreferrer" className="truncate text-sm text-white/82 hover:text-[#F1E2CC]">{d.nom}</a> : <span className="truncate text-sm text-white/82">{d.nom}</span>}</div><button onClick={() => removeDocument(d.id)} className="text-white/30 hover:text-rose-300"><Trash2 size={14} /></button></div>) : <div className="md:col-span-2 max-w-2xl"><Empty icon={FileText} title="Aucune ressource liée." text="Ajoutez un lien vers un brief, un brouillon ou une preuve utile à votre mouvement." /></div>}</div></section>}
  </div>;
}
